# fly.toml app configuration file generated for roast-me-bot on 2023-12-04T03:18:24-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "roast-me-bot"
primary_region = "yul"

[build]

[env]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
